### ISSUE TITLE
download hui.lui.pos and hui.lui.neg files 

### ISSUE THREAD

**Issue by aminebej** [Twitter-Sentiment-Analysis/R#4]
could you please give me a link from which i can download hui.lui.pos and hui.lui.neg files of Worddatabase.r fuction

**Comment by asmitapoddar** [comment]
You can download it from here : https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html

**Comment by amanver16** [comment]
Hi there, Thanks for uploading this project. I'm new to R programming but i've got the sentiment analysis as a project in R. After lots of digging i ended up here and your project is quite understandable for me. Since i'm new, please guide me how should i run this project. I tried running it in r studio by opening the script_running.r file. But i got some errors like package is not found. Please tell me the appropriate way to run the project. Your help will be really appreciable. Thanks :)
