### ISSUE TITLE
Need help in understanding an error relating to CAfile

### ISSUE THREAD

**Issue by kkusum1995** [Twitter-Sentiment-Analysis/R#8]
I'm getting an error message which is -
"Error in function (type, msg, asError = TRUE)  : 
  error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none"
Help me understand what information am i suppose to enter in "cainfo". Please find an information below for reference
> setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
[1] "Using direct authentication"
Use a local file ('.httr-oauth'), to cache OAuth access credentials between R sessions?

1: Yes
2: No

Selection: 1
Adding .httr-oauth to .gitignore
> cred <- OAuthFactory$new(consumerKey='consumerkey', consumerSecret='consumersecret',requestURL='https://api.twitter.com/oauth/request_token',accessURL='https://api.twitter.com/oauth/access_token',authURL='https://api.twitter.com/oauth/authorize')
> cred$handshake(cainfo="cacert.pem")
Error in function (type, msg, asError = TRUE)  : 
  error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none
>

**Comment by asmitapoddar** [comment]
You would need to do your own ROAuth authentication to access the Twitter API. You have to visit Twitter Developer website and make your own Twitter authentication (consumer_key, consumer_secret, access_token, access_secret). 
Also, ensure that there is no path problem of the certificate. Re-check your current working directory by R command, and make sure that the certificate is in your current working directory.

**Comment by kkusum1995** [comment]
I've created my own ROAuth authentcation to access the Twitter API, provided by Twitter itself. I'm trying to understand this error in "cred$handshake(cainfo="cacert.pem")" this specific line.

**Comment by sonali9696** [comment]
@kkusum1995 As far as I remember, I never came across the question "Use a local file ('.httr-oauth'), to cache OAuth access credentials between R sessions?". Maybe it's a new addition. I used to get "Using direct authentication" and then a webpage used to appear with a pan and I was asked to enter the same pin in the R window.

It seems the purpose of the new question is just for caching purposes. Try selecting "No" once and see if it works. If you want to explore caching or if it doesn't work without it, the issue is probably with the file path. You can download the cacert.pem from the internet and keep it in the same location from which you are running it. You can find alternative solutions on stackoverflow.

**Comment by sonali9696** [comment]
For video walkthrough of this authentication you can refer to this video: https://www.youtube.com/watch?v=M09CM4Sqgjw&t=89s

@kkusum1995
